### ISSUE TITLE
zappiehostbuyer not workig

### ISSUE THREAD

**Issue by i-am-xhy** [Skynet2-0/Skynet2.0#58]
Could not complete the transaction because an error occurred:
pop from empty list
Failed to buy the VPS...
Thursday, 16. June 2016 12:21PM
started up agentCore on child, transferring own funds to child
Traceback (most recent call last):
  File "agent/prototype2_agentCore.py", line 177, in <module>
    main(sys.argv[1:])
  File "agent/prototype2_agentCore.py", line 173, in main
    Prototype2(exitnode, usetestserver)
  File "agent/prototype2_agentCore.py", line 70, in __init__
    ssh = SSH(v.getIP(),v.getSSHUsername(),v.getSSHPassword(),22)
  File "/home/niels/Skynet2.0/ssh/SSH.py", line 42, in __init__
    self.connect(port=port)
  File "/home/niels/Skynet2.0/ssh/SSH.py", line 66, in connect
    self.client.connect(sshhost, username = user, password = pwd, port=port)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 296, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 200, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
socket.gaierror: [Errno -5] No address associated with hostname

**Comment by Robdeprop** [comment]
This has been fixed. See the pull request for ZappiehostFix2
