### ISSUE TITLE
Prototype2 crashes

### ISSUE THREAD

**Issue by Robdeprop** [Skynet2-0/Skynet2.0#60]
Prototype2 crashes when trying to install via SSH. I think it already crashed before Zappiehost was even done preparing the VPS.

This is what happened:

rob@Rob-VirtualBox:~/Skynet2.0$ PYTHONPATH=${PYTHONPATH}:. python agent/prototype2_agentCore.py -x False -t False
ERROR:TunnelMain:Yappi not installed, profiling options won't be available
failed to load settings.json, do not expect this program to run properly without it
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
[
    "1Xy9A6bRMmFYzPXyGnM1WZjaes8D3Rdsk"
]

<_sre.SRE_Match object at 0x7f2871c01098>
using already existing wallet
Error: Cannot read config file. /home/rob/.electrum
Daemon already running
Error: Cannot read config file. /home/rob/.electrum
fetching genetic code
Starting up a child server
Bitcoin amount to transfer: 0.006097
To wallet: 17PSr7oQsL9ze1JeaeJaSg9U5Ej1XE8oJy
Username:BGc@ymlWjc.eu
Password:nKKubNXnVLBZdegqvwsOMtEbJmlpkNzb
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
[
    "1Xy9A6bRMmFYzPXyGnM1WZjaes8D3Rdsk"
]

<_sre.SRE_Match object at 0x7f2871c01bf8>
using already existing wallet
Error: Cannot read config file. /home/rob/.electrum
Daemon already running
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
Error: Cannot read config file. /home/rob/.electrum
[
    true, 
    "44700b2464ff62a93fb6395ca25fb6ce4fb78b167a4052ded7ec303b9fd78729"
]
starting installon child
Friday, 17. June 2016 10:28AM
starting the installation procedure
Traceback (most recent call last):
  File "agent/prototype2_agentCore.py", line 177, in <module>
    main(sys.argv[1:])
  File "agent/prototype2_agentCore.py", line 173, in main
    Prototype2(exitnode, usetestserver)
  File "agent/prototype2_agentCore.py", line 64, in __init__
    bc.getChild('prototype2', 'prototype2_agentCore.py')
  File "/home/rob/Skynet2.0/agent/Birthchamber.py", line 63, in getChild
    self.install_and_run_child(d, vpsname, otherBranch, otherCore)
  File "/home/rob/Skynet2.0/agent/Birthchamber.py", line 74, in install_and_run_child
    self.installChild(otherBranch)        
  File "/home/rob/Skynet2.0/agent/Birthchamber.py", line 119, in installChild
    i = Installer(self.vps.getIP(),self.vps.getSSHUsername(),self.vps.getSSHPassword(),22)
  File "/home/rob/Skynet2.0/ssh/install.py", line 32, in __init__
    self.ssh = SSH(hostip, user, password, port)
  File "/home/rob/Skynet2.0/ssh/SSH.py", line 42, in __init__
    self.connect(port=port)
  File "/home/rob/Skynet2.0/ssh/SSH.py", line 66, in connect
    self.client.connect(sshhost, username = user, password = pwd, port=port)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out

**Comment by i-am-xhy** [comment]
locally added ssh reconnects on timeout.
however a real fix would be for the buyers to only terminate once the server is actually online
